FROM node:20-alpine AS base

RUN apk add --no-cache nginx

RUN corepack enable \
    && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

FROM base AS builder

WORKDIR /app

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

FROM nginx:stable-alpine AS runner

RUN rm -rf /usr/share/nginx/html/*

COPY /deployment/testing/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]