name: "Bug report"
description: "Report a reproducible problem with the platform"
title: "[Bug]: <concise summary>"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve the AI Interview Platform. Please provide as much detail as you can so we can investigate quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "What happened? Provide a high-level overview of the issue."
      placeholder: "The candidate dashboard fails to load when ..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "Provide the exact steps someone else can follow to encounter the bug."
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "What should have happened instead?"
      placeholder: "The dashboard should show ..."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "What actually happened? Include errors, stack traces, or logs if available."
      render: shell
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Where did you see the issue? Include app version, branch, browser, OS, etc."
      placeholder: "main branch @ commit abc123, Chrome 124 on macOS 14.4"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Screenshots, recordings, or other context that helps us reproduce the bug."
      placeholder: "Any other helpful notes..."
